Fix readme and jsx check missing
bouvet-apps/xp-tool pull request #9
Opened 2023-02-02 08:49 UTC by vi-h

2023-02-03 08:29 UTC, PeterSund approved these changes

2023-02-14 18:39 UTC, jonaslepsoy approved these changes

2023-02-20 08:06 UTC, dholmen requested changes

2023-02-20 08:06 UTC, dholmen commented on package.json
> +  "version": "2.0.1-B16",
We're still not quite at 2.0.0 stable release, so this should be 2.0.0-B17

2023-02-20 08:23 UTC, dholmen approved these changes

2023-02-20 08:24 UTC, merged